### ISSUE TITLE
In ServiceProvider.php line 84: Trying to access array offset on value of type null

### ISSUE THREAD

**Issue by dodancs** [DarkaOnLine/SwaggerLume#82]
Hey,

I just tried to use this for my new empty Lumen project on version 5.7.6.

I added all the lines mentioned, then tried to run `php artisan swagger-lume:publish-config` and I got the following response:

```
In ServiceProvider.php line 84:

  Trying to access array offset on value of type null 
```

**Comment by dodancs** [comment]
Update: Fixed by rolling back the version of PHP to 7.3

**Comment by sainivipin** [comment]
Hi,
I am new to laravel, when i install my project(lumen) locally and hit postman then i see the following error.

In ServiceProvider.php line 84:  Trying to access array offset on value of type null

I have read many posts on google but all says to use *isset* so i did but unfortunately issue still persist therefore i request you to please guide me to resolve it.

I have the following setting in my composer.json

PHP:">=7.3"
laravel/lumen-framework:"5.5.*"

Thanks!

**Comment by hhxsv5** [comment]
```php
// in bootstrap/app.php
$app->configure('view');
```
